### PR TITLE
Automatically terminate execution of example/historic_data once all data is received

### PR DESCRIPTION
**Pull request by falconed**
Exit historic_data once a response (of any kind) is received for each request that was sent.

### CODE REVIEW

**Comment by topofocus** [comment]
Hi,
nice work.
Can you write a test for the improvement for the connection-class?

I suggest to merge this into the AR4-Branch too.

**Comment by falconed** [comment]
Done!  I moved the message resolution logic to the IB::Messages::Incoming::AbstractMessage class for easier testing and to keep the connection class' responsibilities down.  Let me know if you disagree with that move though.  

I'll shoot you a separate PR for AR4.  There was a minor merge conflict in some comments.

Thanks for the feedback!

**Comment by topofocus** [comment]
Just tried the original example (of the stable branch). 
Is it right that this is broken due to this error message:

    `block in <main>': undefined method `+' for nil:NilClass (NoMethodError)
	from ib-ruby/lib/ib/connection.rb:281:in `call'

And your code fixes this?

Then we have to clarify, when to use 

    ib.subscribe([ messageclass, messageclass] ) do |msg|
    
and when

    ib.subscribe( messageclass, messageclass )  do |msg|


In Connection#subscribe the arguments are treated as array anyway.
Actually I don't see the advantage of using an array as parameter.

**Comment by topofocus** [comment]
I added a slightly modified version to the AR4-Branch. Your suggestions are applied.
Please review and change if nessesary

**Comment by ricpruss** [comment]
Okay so I took sometime today to pull this down and try run the spec's on it.  It seems to break alerts so I did not merge it.

 Message received from IB
    behaves like Alert message
      example at ./spec/ib/messages/incoming/alert_spec.rb:4 (FAILED - 21)
      example at ./spec/ib/messages/incoming/alert_spec.rb:5 (FAILED - 22)
      example at ./spec/ib/messages/incoming/alert_spec.rb:6 (FAILED - 23)
      has class accessors as well (FAILED - 24)
      message_type
        example at ./spec/ib/messages/incoming/alert_spec.rb:7 (FAILED - 25)
      message_id
        example at ./spec/ib/messages/incoming/alert_spec.rb:8 (FAILED - 26)
      version
        example at ./spec/ib/messages/incoming/alert_spec.rb:9 (FAILED - 27)
      data
        example at ./spec/ib/messages/incoming/alert_spec.rb:10 (FAILED - 28)
      error_id
        example at ./spec/ib/messages/incoming/alert_spec.rb:11 (FAILED - 29)
      code
        example at ./spec/ib/messages/incoming/alert_spec.rb:12 (FAILED - 30)
      message
        example at ./spec/ib/messages/incoming/alert_spec.rb:13 (FAILED - 31)
      to_human
        example at ./spec/ib/messages/incoming/alert_spec.rb:14 (FAILED - 32)

**Pull request closed without merging**
