### PR TITLE
Fixing connection_spec.rb to work with rspec 3.2

### PR DESCRIPTION
**Pull request by ricpruss**
Fixed the syntax problems with should still remain in the spec.

Both:
rspec spec/ib/connection_spec.rb
rspec -rdb spec/ib/connection_spec.rb

Run green now.
For -rdb option you need to run rake db:setup prior to running the test.
Will clean up the other specs when time allows.

### CODE REVIEW

**Comment by topofocus** [comment]
Richard, nice work.
but can you remove the 'pp'-control-statement in message-helper (row 25) before we merge it?

**Comment by ricpruss** [comment]
Closing this pull request because I cannot find the magic button to get the third commit documenting not using the helpers into this.

**Comment by ricpruss** [comment]
Hey Topofocus I will create this again but when I do it now I keep getting an error 500. So I sent a support request to the github folks and I will do it when we figure out what is causing the error.

**Comment by ricpruss** [comment]
Github fixed the bug and now all three commits are showing, including the last one where I try documented where I went to instead of adding those helper messages.

**Pull request merged**
